# Generated by Django 3.1.2 on 2022-02-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postitem',
            old_name='user',
            new_name='user_id',
        ),
    ]
