# Generated by Django 3.1.2 on 2022-02-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220212_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
