# Generated by Django 3.1.2 on 2022-02-15 20:53

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220215_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='postimages/', verbose_name='Image'),
        ),
    ]
