# Generated by Django 3.1.2 on 2022-02-15 21:09

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220215_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='postimages/', verbose_name='Image'),
        ),
    ]
