# Generated by Django 3.1.2 on 2022-02-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220215_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postitem',
            name='title',
        ),
        migrations.AlterField(
            model_name='postitem',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
