# Generated by Django 3.1.2 on 2022-02-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220215_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentitem',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='commentitem',
            old_name='user',
            new_name='user_id',
        ),
    ]
