# Generated by Django 3.1.2 on 2022-02-22 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220217_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postitem',
            options={'ordering': ['-created']},
        ),
    ]
