# Generated by Django 3.1.2 on 2022-02-27 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20220222_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='post_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsitems', related_query_name='commentitem', to='posts.postitem'),
        ),
        migrations.AlterField(
            model_name='commentitem',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsitems', related_query_name='commentitem', to=settings.AUTH_USER_MODEL),
        ),
    ]
