# Generated by Django 3.1.2 on 2022-02-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220227_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentitem',
            name='username',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
    ]
