# Generated by Django 3.1.2 on 2022-03-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_commentitem_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
