# Generated by Django 3.1.2 on 2022-03-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_commentitem_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postitem',
            name='username',
        ),
    ]
